### ISSUE TITLE
synthtool keeps files that were removed in updated protos

### ISSUE THREAD

**Issue by jkwlui** [googleapis/synthtool#216]
Encountered this [issue](https://github.com/googleapis/nodejs-talent/pull/29#issuecomment-477755487) generating the nodejs-talent library today (caught indirectly by Node.js's docs-test).

In the latest upstream commit to googleapis (https://github.com/googleapis/googleapis/commit/5fe8a4f65b8606b827cb28cd437cf4d42b4f9920), `ResumeService` was removed entirely from the proto definitions. I know at least in Node.js and Python, the files associated with `ResumeService` still lingers in the repo.

I had to remove the gapic and protos directories and re-run synthtool locally to me to see that the files are being deleted.

This should not be a breaking behaviour, because the removed service client is removed from the exports in `{version}/index.js`, so users would not be able to `require` the client anyways, unless as @busunkim96 points out if they do weird, unsupported things like requiring the client using the direct file system path.

We're currently adding a bunch of files in addition to those generated by synthtool, so a `rm -rf * && synthtool` is out of the question.

Proposals:
1. Record files generated in `synthtool.metadata` and if a new generation doesn't yield files previously generated, then remove them.

1. Specifically target generated gapic directories, knowing that we do not add additional files to them and generate into the directory from a clean state.

**Comment by SurferJeffAtGoogle** [comment]
I implemented a solution by examining generated file time stamps but that solution was flawed because copying files usually preserves the time stamps.  So I rolled back the solution.

@fhinkel and @bcoe and @JustinBeckwith recently suffered due to this issue still existing, so I'm re-opening it and trying a new strategy: using https://pypi.org/project/watchdog/ to observe file system events.
