### ISSUE TITLE
old synth.metadata files not compatible with recent changes

### ISSUE THREAD

**Issue by bcoe** [googleapis/synthtool#407]
I noticed this error when running `synthtool`:

```bash
google.protobuf.json_format.ParseError: Message type "yoshi.synth.metadata.Metadata" has no field named "combinedCommitLog".
 Available Fields(except extensions): ['updateTime', 'sources', 'destinations', 'newFiles']
```

:point_up: works fine if I delete the file and regenerate.

**Comment by SurferJeffAtGoogle** [comment]
I looked at the commit history for the proto definition:
https://github.com/googleapis/synthtool/commits/master/synthtool/protos/metadata.proto

And I see that a `combined_commit_log` field was never committed.

I think this may have ended up in the metadata of nodejs-vision, because I frequently use that repo while testing.  Sorry.
