### ISSUE TITLE
php build runs out of memory

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/synthtool#527]
See https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fphp/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fphp/KOKORO/e31c667a-37a1-4ac2-93b8-f6ef39c37bed/1588761590451/build%20%23663/Targets?target=github%2Fsynthtool&drilldownTab=tests

**Comment by chingor13** [comment]
Note: this is also happening for the Java autosynth job.

I am testing out upgrading bazel to see if that has any effect.

**Comment by chingor13** [comment]
We determined that bazel leaves running servers in the background and will re-use the server if it's launched from the same base directory. In this case, we were cloning googleapis into a temporary directory for each repo and these running bazel servers were consuming enough memory that the machine would OOM before finishing.

Fixed in #532
