### ISSUE TITLE
Strange delays in node.js template update PRs

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#697]
I'm looking at this PR right here:
https://github.com/googleapis/nodejs-phishing-protection/pull/171

We've already approved/merged dozens of these PRs in other libraries, and it's unclear to me why this one is magically appearing on nodejs-phising-protection *days* after previous PRs.  

- **2020-07-27** - The PR is [opened on nodejs-phising-protection](https://github.com/googleapis/nodejs-phishing-protection/pull/171)
- **2020-07-23** - A PR from the same origin change happened [4 days earlier](https://github.com/googleapis/nodejs-asset/pull/371) on nodejs-asset
- **2020-07-22** - The origin commit was opened on synthtool with the template update

We use batch tools to do approves, renames, and label adding.  When the PRs get spread out like this, it has a pretty negative effect on our workflow.  

If I had to bet a dollar, I would guess autosynth is experiencing timeouts or errors halfway through execution, and stopping.

**Comment by alexander-fenster** [comment]
Timeout indeed happens:

![image](https://user-images.githubusercontent.com/4015807/88598456-29f8f800-d01e-11ea-88f4-3c17f4ab2045.png)

The problem that I see is that GAPIC libraries can take between 8 and 15 minutes to run synth which is TOO LONG (it works much faster on my laptop). I can only see the general log and I can't see individual logs for one library to check which step takes that much time (sponge says "file not found" if I try to open a log for a specific library).

**Comment by danoscarmike** [comment]
@SurferJeffAtGoogle would you mind having a poke at this one?

**Comment by bcoe** [comment]
we have a plan  in motion to address this. The problem is that if a project has no proto changes for a long period of time, the metadata tracked in `synth.py` gets stale, the plan of action is to store the new value on an alternate branch.

**Comment by SurferJeffAtGoogle** [comment]
The issue Ben mentioned contributes to slowness, to be sure.  However, all
the nodejs repos have been updated in the past week so autosynth is
searching through a relatively small number of past commits.  Also, we
decided against storing metadata in a branch in a meeting last Wednesday.

**Comment by SurferJeffAtGoogle** [comment]
I investigated a little more deeply.  Summary: **npm is very slow.**

I observed that `npm install` took > 1 minute while generating the library for the relatively simple gcp-metadata API.  See the logs below.

I confirmed that my cache directory `~/.npm` was not wiped out between apis, so npm should be fetching packages from the cache.

Additionally, I observed that linting the code took > 30 seconds.

90 seconds to `npm install` and `npm fix` multiplied by 90 APIs yields 135 minutes, which is right about what we see for a full autosynth run with no changes:
https://fusion.corp.google.com/runanalysis/info/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fnodejs/prod%3Acloud-devrel%2Fclient-libraries%2Fautosynth%2Fnodejs/KOKORO/46f39e56-2d48-4dfc-8fcc-e5cf5f484e53/1596798248715/build%20%23818/Targets

When the nodejs template changes, and autosynth has to synthesize say 5 times per API, then 5 * 135 = 675 minutes, which is greater than the current timeout.

I see no way to make npm faster.  Even if it pulls everything from cache, it still has to copy as much as 1 GB from the cache directory to the local directory.  Do @JustinBeckwith or @bcoe see a way to make npm faster?

If there's no reasonable way to make npm faster, then we need to change autosynth config so it synthesizes APIs in parallel.  That's not my first choice because it would break the current "add a synth.py to your repo and autosynth will find it" story, but we could make it work.

For comparison, Ruby can generate and lint all the code for a library in about 10 seconds.

```
2020-08-12 12:09:38,052 synthtool [DEBUG] > Installing dependencies...
DEBUG:synthtool:Installing dependencies...
npm WARN deprecated ts-simple-ast@12.4.0: NOTICE: ts-simple-ast has been renamed to ts-morph and version reset to 1.0.0. Switch at your leisure...
npm WARN deprecated viz.js@1.8.2: no longer supported
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> core-js@2.6.11 postinstall /usr/local/google/home/rennie/.cache/synthtool/gcp-metadata/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> @compodoc/compodoc@1.1.11 postinstall /usr/local/google/home/rennie/.cache/synthtool/gcp-metadata/node_modules/@compodoc/compodoc
> opencollective-postinstall || exit 0

[96m[1mThank you for using @compodoc/compodoc![96m[1m
[0m[96mIf you rely on this package, please consider supporting our open collective:[22m[39m
> [94mhttps://opencollective.com/compodoc/donate[0m


> gcp-metadata@4.1.4 prepare /usr/local/google/home/rennie/.cache/synthtool/gcp-metadata
> npm run compile


> gcp-metadata@4.1.4 precompile /usr/local/google/home/rennie/.cache/synthtool/gcp-metadata
> gts clean

version: 12
Removing build ...

> gcp-metadata@4.1.4 compile /usr/local/google/home/rennie/.cache/synthtool/gcp-metadata
> tsc -p .

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/live-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 993 packages from 491 contributors and audited 999 packages in 54.659s

64 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

2020-08-12 12:10:41,292 synthtool [DEBUG] > Running prelint...
DEBUG:synthtool:Running prelint...

> gcp-metadata@4.1.4 prelint /usr/local/google/home/rennie/.cache/synthtool/gcp-metadata
> cd samples; npm link ../; npm install


> gcp-metadata@4.1.4 prepare /usr/local/google/home/rennie/.cache/synthtool/gcp-metadata
> npm run compile


> gcp-metadata@4.1.4 precompile /usr/local/google/home/rennie/.cache/synthtool/gcp-metadata
> gts clean

version: 12
Removing build ...

> gcp-metadata@4.1.4 compile /usr/local/google/home/rennie/.cache/synthtool/gcp-metadata
> tsc -p .

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/live-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 999 packages in 20.67s

64 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

/usr/local/google/home/rennie/Downloads/node-v12.18.0-linux-x64/lib/node_modules/gcp-metadata -> /usr/local/google/home/rennie/.cache/synthtool/gcp-metadata
/usr/local/google/home/rennie/.cache/synthtool/gcp-metadata/samples/node_modules/gcp-metadata -> /usr/local/google/home/rennie/Downloads/node-v12.18.0-linux-x64/lib/node_modules/gcp-metadata -> /usr/local/google/home/rennie/.cache/synthtool/gcp-metadata
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 137 packages from 79 contributors and audited 151 packages in 9.315s

64 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

2020-08-12 12:11:13,747 synthtool [DEBUG] > Running fix...
```

**Comment by JustinBeckwith** [comment]
Yup, those numbers are not a bad dream.  `npm install` is downloading and installing all that gunk, and actually does `npm run compile` so it's building as well.  The `npm run lint` command is taking so long because it's actually `cd`ing into the samples directory, installing and linting, and then finally running `gts check`.  The `gts check` step is likely only a second or two.  

I see two realistic approaches here:
- parallelization
- eliminate the need to run `npm install` or `npm run fix` at all as part of synthesis

At this stage, I think @alexander-fenster has the best handle on why `npm install` is required as part of synth in a post-generation step.  Any way we could ... not?

**Comment by JustinBeckwith** [comment]
On parallelization - @SurferJeffAtGoogle I've had this idea bouncing around in my head for a while, where "what if" each repository that needed synthool owned it's own kokoro nightly cron.  Instead of trying to queue up all of these in a single job, could we just make the local kokoro config for running it's nightly synth job?

**Comment by bcoe** [comment]
> npm install took > 1 minute

I'm surprised  by these performance  #s; as our dependency count isn't out of control.

I wonder if npm has been seeing some performance issues recently, which could partially explain the behavior we're seeing.

> "what if" each repository that needed synthool owned it's own kokoro nightly cron.

A middle ground that I used at  npm when services reached capacity (before we were ready for a major refactor) was to simply run N copies, and have each copy know their value in the cluster. You can then simply have each service use modulo to decide whether a given item of work in an array is theirs. So, if we have:

```
const libraries = [
  "nodejs-storage",
  "nodejs-bigquery",
  "nodejs-phishing-protection",
  "nodejs-automl"
]
```

and we ran `synthtool  id = 0`,  and `synthtool id = 1`, `count = 2`, you just do:

```
libraries.forEach((lib, index) => {
  if ((index + id) % count === 0) {
     synthesis(lib)
  }
})
```

It's ugly, in that each node int he cluster needs to know about the cluster configuration, it's nice in that you can create a distributed system easily from something that wasn't designed for it.

**Comment by alexander-fenster** [comment]
@JustinBeckwith I missed this, so here are my thoughts. We run install (several times - once for the library, once for samples) only to be able to lint. If we don't run install in samples, we won't be able to lint properly (because samples require `@google-cloud/library-being-generated`). If we ignore linting errors, we'll start generating broken libraries (we've been there).

I was thinking of installing all the packages needed _just_ to run `gts fix` globally – no `npm install`, no compilation, no nothing, just `npm install -g google-gax gts`, then `npx compileProtos src` (we still need this one), and `npx gts fix`. It would've worked, if not the samples problem. Not sure at this point how we can make it better.

**Comment by JustinBeckwith** [comment]
I'm kinda convinced at the moment we should parallelize autosynth by creating kokoro jobs for each repository.  Running `npm install` isn't an unreasonable requirement for generation.

**Comment by SurferJeffAtGoogle** [comment]
Parallelizing the build looks like the only workable option.  I was hoping
there was a better option because it's going to make setting up a new
repository much more difficult.  Today, the only necessary step is to add a
synth.py to your repo.  Maybe I can use Ben's strategy of running N copies
to preserve that benefit.

**Comment by JustinBeckwith** [comment]
🥳
