### ISSUE TITLE
Synthtool is trying to delete package.json

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/synthtool#757]
Looking at this PR here:
https://github.com/googleapis/nodejs-automl/pull/450

It looks like autosynth is trying to delete `samples/package.json`, which is very much needed for the package to operate.  Not sure how it's happening 🤷

**Comment by JustinBeckwith** [comment]
FYI @bcoe

**Comment by SurferJeffAtGoogle** [comment]
Investigating...

**Comment by SurferJeffAtGoogle** [comment]
The only way synthtool can learn what files are being generated is to observe what files have been touched during the generation process, because `synth.py` is an opaque script that provides no insight into dependencies or products.

In the previous [PR #448](https://github.com/googleapis/nodejs-automl/commit/9772dcab53a3257ba633e0cfa9c4cf03b8506005#diff-4bb83488be1d7051935e29fa36a1a4c8), regenerating the code via synthtool modified `package.json`.  The change was a white-space-only change, so I suspect it was a linter.  Was a new version of the nodejs linter introduced?

The change to `package.json` in [PR #448](https://github.com/googleapis/nodejs-automl/commit/9772dcab53a3257ba633e0cfa9c4cf03b8506005#diff-4bb83488be1d7051935e29fa36a1a4c8) caused synthtool to think that `package.json` must have been generated, so it got added to the `generatedFiles` list in `synth.metadata`.

In [PR #450](https://github.com/googleapis/nodejs-automl/pull/450), synthtool regenerated the code and finds nothing touched `package.json`.  So, synthtool concluded that whatever was generating `package.json` stopped generating it.

I see a number of possible solutions to the problem.

1.  Make synth.py touch all the files that the linter visits.
2.  Make synth.py run the linter on generated code exclusively, not on manually written sample code.
3.  Update synth.py to call a new function `synthtool.stop_tracking_obsolete_files_now()` after the code generation step has run, and before the linter runs.
4.  In synth.py, specify a list of files or directories that autosynth should ignore when collecting the list of generated files.
5.  Stop tracking obsolete files.  Turn off this feature. 

As a temporary work-around for this PR and similar PRs,

1.  Create and merge a new PR that removes `package.json` from the list of `generatedFiles` in `synth.metadata`.
2.  Check the boxes to regenerate PRs [#449](https://github.com/googleapis/nodejs-automl/pull/449) and [#450](https://github.com/googleapis/nodejs-automl/pull/450).

**Comment by SurferJeffAtGoogle** [comment]
Discussed in meeting, and @bcoe will implement one of the solutions listed above.

**Comment by bcoe** [comment]
from discussion offline: we'd like to turn of file deletion until we can put some actual time against this problem... I think we might ultimately end up with a separate cleanup step.

**Comment by danoscarmike** [comment]
@bcoe @SurferJeffAtGoogle what's the latest here?

**Comment by SurferJeffAtGoogle** [comment]
We disabled obsolete file tracking for nodejs, so it's no longer an issue.
