### ISSUE TITLE
Templates files should use .jinja2 file extension

### ISSUE THREAD

**Issue by chingor13** [googleapis/synthtool#761]
For new contributors, it's not necessarily clear that all files in the templates folders are treated like jinja templates. This should also help developers using IDEs with syntax highlighting.

By convention, we should take any `filename.ext.jinja2` and use it to generate a `filename.ext` file. For files without `.jinja2` file extensions, we should simply copy.

Example: updating a GitHub actions workflow yaml may have something like `{{ secrets.GITHUB_TOKEN }}` which needs to be escaped for jinja templating. It's not clear to the contributor that the sequence needs to be treated as a jinja template and escaped.

**Comment by stephaniewang526** [comment]
This would be useful -- see my [commit](https://github.com/googleapis/synthtool/pull/760/commits/436db8946261418ba3fe65419c613af4f539bb69) to fix jinja issue only after discussing w Jeff

**Comment by tmatsuo** [comment]
There are some instances where we use `j2` file extention, so if we only treat `jinja2`, it will broke.

https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/docs/conf.py.j2

Also, because we don't know which existing files are jinja template, this should be an opt-in feature.
